### PR TITLE
Review app linked to business page + small modifications

### LINKED ISSUE #136: Update review App after professional public URL is created
Timeline:
1. Professional public URL (the one that client users can view) is created
2. Merged into main
3. `review` App is updated - design, URLs, etc.

### PR DESCRIPTION
**Pull request by guybeckenstein**
Resolves #136 

##
1. Fixed issues with user menu bar (logged-in user modifications that were made in PR #125 were overwritten)
2. Fixed issues with sidebar. Guest cannot see sidebar. This was done in `account/profile`
3. Modified professional business page. now professional business page is linked with his all reviews page. On business page you can see how many reviews are 5, 4, 3, 2, or 1, and average rating. 
4. All reviews page is linked to business page
5. Added sidebar to all reviews page and reviews form page
##

### CODE REVIEW

**Review by TalReinfeld — APPROVED** [review]
LGTM

**Review by idosinger98 — APPROVED** [review]
LGTM

**Review by patrisiakaplun — APPROVED** [review]
LGTM

**Review by idoyek — APPROVED** [review]
LGTM

**Review by OfirBachar — APPROVED** [review]
LGTM

**Review by Yarboa — APPROVED** [review]
LGTM

**Comment by Yarboa** [comment]
need to rebase?

**Comment by guybeckenstein** [comment]
> need to rebase?

I resolved conflicts

**Pull request merged**
