### PR TITLE
Add ERD diagram

### LINKED ISSUE #24: Create Entity Relationship Diagram
A graphical representation that depicts relationships among people, objects, places, concepts or events within an information technology (IT) system of Pro4U

### PR DESCRIPTION
**Pull request by idosinger98**
Resolve #24

### CODE REVIEW

**Review by idoyek — APPROVED** [review]
LGTM

**Review by OfirBachar — APPROVED** [review]
LGTM

**Review by TalReinfeld — APPROVED** [review]
LGTM

**Review by OfirBachar — APPROVED** [review]
LGTM

**Review by guybeckenstein — APPROVED** [review]
LGTM

**Review by OfirBachar — COMMENTED** [review]
I think we should add to the Appointment - Appointment documentation.
In addition, we should add to the Professional - Customers list, incomes list.

**Comment by idosinger98** [comment]
I don't think the changes need to be made because you can see the professional's client list through the Appointment table

**Comment by Yarboa** [comment]
Is the User refers to?  
from django.contrib.auth.models import User

In that case it is not visible.

What approach will you choose for the models.user extension? 

Think of Profiles in your App,
It should not implemented from the beginning, but should be takes care in design  

https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html

**Review by Yarboa — COMMENTED** [review]
Please refer to my comments

**Review by OfirBachar — COMMENTED** [review]
1. Yes, the User refers to from django.contrib.auth.models import User. We are doing that by adding note. Is there anything else that needs to be done to indicate this?
2. We chose Option 2: Using One-To-One Link With a User Model (Profile).

**Comment by Yarboa** [comment]
> 1. Yes, the User refers to from django.contrib.auth.models import User. We are doing that by adding note. Is there anything else that needs to be done to indicate this?
> 2. We chose Option 2: Using One-To-One Link With a User Model (Profile).

Please change the User header of the entity to Django User
Based on the article mentioned, it seems that you plan to add more fields then  Django User contains, Please reread and check if that your proposal model entities cover this part

**Comment by idosinger98** [comment]
I think he will have the option on the registration page to click on which type of user he wants and according to that the appropriate fields will open for him to fill in.
The question is whether it should be added to the ERD?

**Comment by patrisiakaplun** [comment]
Do you think adding an enum field in the user table can solve the problem?
I am asking because we chose the user to be Django user And I wonder if it is ok to add other fields to this table?

**Review by OfirBachar — COMMENTED** [review]
Do you mean to add another Enum field in the User that will describe the type of user (currently a professional or a customer)?

**Comment by Yarboa** [comment]
> Do you mean to add another Enum field in the User that will describe the type of user (currently a professional or a customer)?

I am just saying, in case you used UserProfile profile, it is not visible in the ERD.
Once you will rethink of it, maybe you will find the solution, which is not visible to me.
Once you will describe it in a model, all can be visible

**Comment by brochwerger** [comment]
build-in ... again check for typos (it is built-in)

**Comment by Yarboa** [comment]
Reopening for the learning @idosinger98 
Please follow this
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

**Comment by Yarboa** [comment]
Reopening for the learning @idosinger98
Please follow this
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally


Ok we can nor reopen here you created new branch

**Pull request closed without merging**
