### PR TITLE
update ERD

### LINKED ISSUE #29: update ERD
We added new tables and fields, so the ERD needs to be updated.

### PR DESCRIPTION
**Pull request by idosinger98**
Resolve #29

### CODE REVIEW

**Review by TalReinfeld — APPROVED** [review]
LGTM

**Review by OfirBachar — APPROVED** [review]
LGTM

**Review by guybeckenstein — APPROVED** [review]
LGTM

**Review by patrisiakaplun — COMMENTED** [review]
If you have already changed the names of the tables, I think you should keep the same format. A new word starts with a capital letter or a dash separates each word

**Review by idoyek — APPROVED** [review]
LGTM

**Review by TalReinfeld — APPROVED** [review]
LGTM

**Review by OfirBachar — APPROVED** [review]
LGTM

**Review by Yarboa — APPROVED** [review]
LGTM

**Pull request merged**
