### PR TITLE
Fixed 0002_test_data.py file

### PR DESCRIPTION
**Pull request by guybeckenstein**
Fixed _0002_test_data.py_ file

### CODE REVIEW

**Review by Yarboa — COMMENTED** [review]
@guybeckenstein 
Is this solving failures of #55 and #56 ?

In that case you need to push team for review

**Review by patrisiakaplun — APPROVED** [review]
LGTM

**Review by idosinger98 — APPROVED** [review]
LGTM

**Review by Yarboa — APPROVED** [review]
LGTM

**Pull request merged**
