### PR TITLE
Add reservation app

### LINKED ISSUE #36: Add reservation app
We need a reservation app so customers can book an appointment with a professional.

### PR DESCRIPTION
**Pull request by idosinger98**
Add reservation app
Create Appointment, TypeOfJob, Schedule models

At the time of creating this PR we still don't have the Client and Professional apps.

The model has foreign keys from client and professional which have not been merged yet, so for now it was added within a comment.

When we add the Client and Professional apps, I'll make the necessary changes in the models.py.

Resolve #36

### CODE REVIEW

**Comment by guybeckenstein** [comment]
This does not bypass Flake8 automation

**Comment by idosinger98** [comment]
> This does not bypass Flake8 automation

Fixed

**Review by idoyek — APPROVED** [review]
LGTM

**Review by guybeckenstein — APPROVED** [review]
LGTM

**Review by OfirBachar — APPROVED** [review]
LGTM

**Comment by brochwerger** [comment]
Seems to me that not having the Client and Professional yet limits the actual application functionality. I suggest, instead of waiting for proper login functionality, have fixed set of clients and professionals, that you can manually add to the tables, then you can develop the rest of the application independently from login functionality.

**Comment by idosinger98** [comment]
> Seems to me that not having the Client and Professional yet limits the actual application functionality. I suggest, instead of waiting for proper login functionality, have fixed set of clients and professionals, that you can manually add to the tables, then you can develop the rest of the application independently from login functionality.

Done.

**Review by Yarboa — APPROVED** [review]
LGTM

**Comment by idosinger98** [comment]
> LGTM Please rebase, merge conflicts

Done

**Review by Yarboa — APPROVED** [review]
LGTM

**Pull request merged**
