### PR TITLE
Create a page for making an appointment with a professional

### LINKED ISSUE #131: Creating a page to make an appointment with a professional

### PR DESCRIPTION
**Pull request by idosinger98**
The changes I made are:

1. I added a page that confirmed the appointment that the client clicked on.

2. I added a calendar for the client that sees the available hours to make an appointment with a certain professional
 (when what is colored purple means that the professional is not available and you cannot click on it and when the time is in blue it means that the professional is available and you can click on it).

3. I added tests

Resolve #131 

image
image

### CODE REVIEW

**Review by idosinger98 — COMMENTED** [review]
@Yarboa Can you help me understand why it doesn't recognize pytz I added it to the pipfile

**Comment by Yarboa** [comment]
> @Yarboa Can you help me understand why it doesn't recognize pytz, I added it to the pipfile

https://redhat-beyond.slack.com/archives/C04TLCD78UT/p1685436036553899

**Review by patrisiakaplun — COMMENTED** [review]
Please add a photo of the page

**Comment by Yarboa** [comment]
> Please add a photo of the page

@patrisiakaplun 
You can always use this 
git fetch upstream pull/132/head:PR_132
Git checkout PR_132

And inside vagrant run your setup.sh
in case of errors the quicket solution is remove the db,sql file

**Comment by idosinger98** [comment]
> Please add a photo of the page

Done

**Comment by idosinger98** [comment]
> please use `make_client` and not `demo_client`. `make_client` is deprecated

Done @guybeckenstein

**Comment by guybeckenstein** [comment]
LGTM

**Review by TalReinfeld — APPROVED** [review]
LGTM

**Comment by Yarboa** [comment]
@idosinger98 please rebase

**Comment by idosinger98** [comment]
> @idosinger98 please rebase

Done @Yarboa

**Review by Yarboa — APPROVED** [review]
LGTM

**Pull request merged**
