### PR TITLE
Adding login page and add tests 

### LINKED ISSUE #78: Adding login page

### PR DESCRIPTION
**Pull request by idosinger98**
The changes that were made:

1. Add login page

2. Add tests to the login page

3. Add base_html

Resolve #78 

image

### CODE REVIEW

**Review by patrisiakaplun — APPROVED** [review]
LGTM

**Review by guybeckenstein — APPROVED** [review]
LGTM

**Comment by Yarboa** [comment]
Please avoid login, 
Sorry, nut i intend to wait with it for later phase

**Comment by idosinger98** [comment]
> Please avoid login, Sorry, nut i intend to wait with it for later phase



> Please avoid login, Sorry, nut i intend to wait with it for later phase



> Please avoid login, Sorry, nut i intend to wait with it for later phase



> 

Ok ,I will put this PR in draft

**Pull request closed without merging**
