### PR TITLE
Add DFD diagram

### PR DESCRIPTION
**Pull request by idosinger98**
Resolve #26

### CODE REVIEW

**Review by idoyek — APPROVED** [review]
LGTM

**Review by patrisiakaplun — APPROVED** [review]
LGTM

**Review by Yarboa — COMMENTED** [review]
Which of the following dataflows does not require Authentications?

**Review by TalReinfeld — COMMENTED** [review]
Yariv I think that we did not  understand the comment, Authentications for what?

**Comment by brochwerger** [comment]
massege ? check English for typos 

Not sure why you need separate appointment and schedule databases

**Comment by Yarboa** [comment]
> Yariv I think that we did not understand the comment, Authentications for what?

SignUp and SignIn 

> Yariv I think that we did not understand the comment, Authentications for what?

SignUp & Login are named as User Authentication
Do you have data flows which are open for non Authenticated Users?

**Comment by Yarboa** [comment]
> _ No description provided. _

@idosinger98 Please update the description through the github UI

**Comment by idosinger98** [comment]
> > _ No description provided. _
> 
> @idosinger98 Please update the description through the github UI

I updated the description

**Comment by idosinger98** [comment]
> > Yariv I think that we did not understand the comment, Authentications for what?
> 
> SignUp and SignIn
> 
> > Yariv I think that we did not understand the comment, Authentications for what?
> 
> SignUp & Login are named as User Authentication Do you have data flows which are open for non Authenticated Users?

Yes a guest can search for a professional and view his profile.

**Comment by TalReinfeld** [comment]
We are updating it now

**Review by TalReinfeld — APPROVED** [review]
LGTM

**Review by Yarboa — APPROVED** [review]
LGTM

**Pull request merged**
