### PR TITLE
Change logic, UI and tests of schedule timings for each professional after login PR merge

### LINKED ISSUE #121: Change logic and tests of schedule timings for each professional after login PR merge

### PR DESCRIPTION
**Pull request by idosinger98**
I adjusted the feature design to be part of the system design.
I added in the tests the option to check whether a user is connected or not.
Resolve #121 
image

### CODE REVIEW

**Review by patrisiakaplun — APPROVED** [review]
LGTM

**Review by Yarboa — COMMENTED** [review]
If this PR is dependent on other PR
Please rebase against the other PR, in case the other PR merged, the changes of this PR will be visible

**Review by guybeckenstein — APPROVED** [review]
LGTM

**Comment by idosinger98** [comment]
> If this PR is dependent on other PR Please rebase against the other PR, in case the other PR merged, the changes of this PR will be visible

Now it is ready for review @Yarboa

**Review by Yarboa — APPROVED** [review]

**Pull request merged**
